export const ERRORS = "ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const PRODUCTS = "PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export  const SUCCESSFUL_REGISTER ="SUCCESSFUL_REGISTER";
export  const FAILURE_REGISTER ="FAILURE_REGISTER";